#!/bin/bash

#PBS -j oe
#PBS -M christopher.jin@unsw.edu.au
#PBS -m ae

#PBS -N seq2stopstart_h1_1
#PBS -l select=1:ncpus=16:mem=124gb
#PBS -l walltime=12:00:00

source ~/.bashrc

cd "$PBS_O_WORKDIR"

conda activate seq2startstop

python seq2startstop.py \
 --fasta /srv/scratch/z5312523/IS1182_target_termcheck/h1_1_remap.fasta \
 --genbank_dir /srv/scratch/treelab/CJ_insertion_sequences/IS1182_target_termcheck/get_genbank/fastas/genbank \
 --blast_db /srv/scratch/treelab/CJ_genomes/blastdbs/nt/nt \
 --output_dir results/